# Environnement: development ou production
environment=production

# Configuration MySQL (développement local)
db.mysql.url=jdbc:mysql://localhost:3306/brasil_burger
db.mysql.user=root
db.mysql.password=

# Configuration Neon PostgreSQL (production)
db.neon.url=jdbc:postgresql://ep-green-flower-a41njh0k-pooler.us-east-1.aws.neon.tech/neondb
db.neon.user=neondb_owner
db.neon.password=npg_ZSfnwt30JeKI

# Options PostgreSQL
db.neon.options=sslmode=require&channel_binding=require