services:
  - type: web
    name: bb-burger-gestionnaire
    runtime: docker
    region: frankfurt
    plan: free
    branch: symfony

    rootDir: .
    dockerContextDir: .
    dockerfilePath: Dockerfile

    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:…?sslmode=require&serverVersion=15"
      - key: CLOUDINARY_CLOUD_NAME
        value: drqsusznh
      - key: CLOUDINARY_API_KEY
        value: "218493326687862"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: MESSENGER_TRANSPORT_DSN
        value: "doctrine://default"
