services:
  - type: web
    name: bb-burger-gestionnaire
    runtime: docker
    rootDir: ./BBBurgerSymfony/BBBurgerSymfony
    dockerContextDir: ./BBBurgerSymfony/BBBurgerSymfony
    dockerfilePath: ./Dockerfile  
    region: frankfurt
    plan: free
    branch: symfony
    
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:endpoint=ep-green-flower-a41njh0k;npg_ZSfnwt30JeKI@ep-green-flower-a41njh0k-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&serverVersion=15"
      
      - key: CLOUDINARY_CLOUD_NAME
        value: drqsusznh
      - key: CLOUDINARY_API_KEY
        value: "218493326687862"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      
      - key: MESSENGER_TRANSPORT_DSN
        value: "doctrine://default"